name: Execution des tests
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Install dependencies
       run: npm install

     - name: Execution test
       run: npx cypress run --spec cypress/e2e/connection.cy.js      



 
