name: Execution des tests
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Install Cypress
       uses: cypress-io/github-action@v6
       with:
        spec: cypress/e2e/connection.cy.js
        browser: chrome

     - name: Generer un rapport
       run: npx cypress run --reporter cypress-mochawesome-reporter



 
